### ISSUE TITLE
softmax kernel error

### ISSUE THREAD

**Issue by guo-hh** [KarhouTam/cuda-kernels#1]
[this loop](https://github.com/KarhouTam/cuda-kernels/blob/9fcb6b86de916c78f6203efacf2b3122f76b7c6c/kernels/softmax/softmax_forward.cu#L140) should add a line `maxVal = bigger`

**Comment by KarhouTam** [comment]
Thx.
Fixed.

**Comment by guo-hh** [comment]
emmm... [this line](https://github.com/KarhouTam/cuda-kernels/blob/1cbda003d7e0166e7fc23aa4c496c8ee5c25f019/kernels/softmax/softmax_forward.cu#L191) also has problem. Because now each thread in the same warp has different `maxval` and the `sumval` is calculated by different `maxval`. I think the correct method is `float maxval_warp = warpReduceMax(maxval); sumval = sumval * exp(maxval - fmaxf(maxval, maxval_warp)); maxval = maxval_warp; sumval = warpReduceSum(sumval)`

**Comment by KarhouTam** [comment]
Thx, fixed again😂.
(But I checked these kernels locally before I push them and no computation error raised. Wonder why.)
